"""Initial schema for the research platform.

Eleven tables: the entity model (issuer, security, filing, financial_fact,
market_snapshot), the computed layer (screening_metric), the index over the
artifacts (harness_run, screen_run, deep_dive) and operations (job, sync_log).

Revision ID: 0001_initial
Revises: 
Create Date: 2026-09-21 20:07:59.949584+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deep_dive',
    sa.Column('deep_dive_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('ticker', sa.String(length=64), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('jurisdiction', sa.String(length=8), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('route', sa.String(length=64), nullable=True),
    sa.Column('red_team_overall', sa.String(length=64), nullable=True),
    sa.Column('agreement_with_harness', sa.String(length=64), nullable=True),
    sa.Column('report', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('provider_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('deep_dive_id')
    )
    op.create_index('ix_deep_dive_ticker', 'deep_dive', ['ticker', 'as_of_date'], unique=False)
    op.create_table('issuer',
    sa.Column('issuer_id', sa.Integer(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=2), nullable=False),
    sa.Column('regulator', sa.String(length=8), nullable=False),
    sa.Column('regulator_issuer_id', sa.String(length=64), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=255), nullable=True),
    sa.Column('fiscal_year_end_month', sa.Integer(), nullable=True),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jurisdiction IN ('US','KR')", name='ck_issuer_jurisdiction'),
    sa.CheckConstraint("regulator IN ('SEC','DART')", name='ck_issuer_regulator'),
    sa.PrimaryKeyConstraint('issuer_id'),
    sa.UniqueConstraint('regulator', 'regulator_issuer_id', name='uq_issuer_regulator_id')
    )
    op.create_table('job',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued','running','completed','failed','cancelled')", name='ck_job_status'),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('idempotency_key', name='uq_job_idempotency')
    )
    op.create_index('ix_job_status_kind', 'job', ['status', 'kind'], unique=False)
    op.create_table('screen_run',
    sa.Column('screen_run_id', sa.String(length=64), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('spec_id', sa.String(length=64), nullable=True),
    sa.Column('backend', sa.String(length=64), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('matched_count', sa.Integer(), nullable=True),
    sa.Column('considered', sa.Integer(), nullable=True),
    sa.Column('spec', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('results', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('code_commit_sha', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('screen_run_id')
    )
    op.create_table('sync_log',
    sa.Column('sync_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('inserted', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('sync_id')
    )
    op.create_table('filing',
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('issuer_id', sa.Integer(), nullable=True),
    sa.Column('regulator', sa.String(length=8), nullable=False),
    sa.Column('form_type', sa.String(length=255), nullable=False),
    sa.Column('reprt_code', sa.String(length=8), nullable=True),
    sa.Column('accession', sa.String(length=64), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('is_amendment', sa.Boolean(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('source_document', sa.String(length=255), nullable=True),
    sa.Column('raw_uri', sa.Text(), nullable=True),
    sa.Column('raw_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuer.issuer_id'], ),
    sa.PrimaryKeyConstraint('filing_id'),
    sa.UniqueConstraint('regulator', 'accession', name='uq_filing_accession')
    )
    op.create_index('ix_filing_issuer_date', 'filing', ['issuer_id', 'filing_date'], unique=False)
    op.create_table('security',
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('issuer_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=64), nullable=False),
    sa.Column('exchange', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('security_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('excluded_reason', sa.String(length=255), nullable=True),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuer.issuer_id'], ),
    sa.PrimaryKeyConstraint('security_id'),
    sa.UniqueConstraint('exchange', 'ticker', name='uq_security_exchange_ticker')
    )
    op.create_index('ix_security_ticker', 'security', ['ticker'], unique=False)
    op.create_table('financial_fact',
    sa.Column('fact_id', sa.Integer(), nullable=False),
    sa.Column('fact_key', sa.String(length=64), nullable=False),
    sa.Column('issuer_id', sa.Integer(), nullable=True),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=64), nullable=True),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('metric_detail', sa.String(length=255), nullable=True),
    sa.Column('reported_label', sa.String(length=255), nullable=True),
    sa.Column('statement', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Numeric(precision=28, scale=4, asdecimal=False), nullable=True),
    sa.Column('unit_kind', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('scale_multiplier', sa.Numeric(precision=28, scale=4, asdecimal=False), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('period_kind', sa.String(length=8), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('segment', sa.String(length=255), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('source_document', sa.String(length=255), nullable=True),
    sa.Column('source_locator', sa.Text(), nullable=True),
    sa.Column('consolidation_basis', sa.String(length=3), nullable=True),
    sa.Column('gaap_status', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=18, scale=8, asdecimal=False), nullable=True),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('is_amended', sa.Boolean(), nullable=False),
    sa.Column('is_restated', sa.Boolean(), nullable=False),
    sa.Column('supersedes_fact_id', sa.Integer(), nullable=True),
    sa.Column('pack_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("consolidation_basis IS NULL OR consolidation_basis IN ('CFS','OFS')", name='ck_fact_consolidation'),
    sa.CheckConstraint("period_kind <> 'fy' OR fiscal_quarter IS NULL", name='ck_fact_fy_has_no_quarter'),
    sa.CheckConstraint("period_kind <> 'quarter' OR fiscal_quarter IS NOT NULL", name='ck_fact_quarter_has_quarter'),
    sa.CheckConstraint("period_kind IN ('instant','quarter','ytd','fy')", name='ck_fact_period_kind'),
    sa.ForeignKeyConstraint(['filing_id'], ['filing.filing_id'], ),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuer.issuer_id'], ),
    sa.ForeignKeyConstraint(['supersedes_fact_id'], ['financial_fact.fact_id'], ),
    sa.PrimaryKeyConstraint('fact_id'),
    sa.UniqueConstraint('fact_key', name='uq_fact_key')
    )
    op.create_index('ix_fact_lookup', 'financial_fact', ['issuer_id', 'metric', 'period_kind', 'period_end', 'consolidation_basis'], unique=False)
    op.create_table('harness_run',
    sa.Column('harness_run_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=64), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('jurisdiction', sa.String(length=8), nullable=True),
    sa.Column('exchange', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('core_score', sa.Numeric(precision=8, scale=4, asdecimal=False), nullable=True),
    sa.Column('ex_valuation_score', sa.Numeric(precision=8, scale=4, asdecimal=False), nullable=True),
    sa.Column('coverage_weight', sa.Numeric(precision=8, scale=4, asdecimal=False), nullable=True),
    sa.Column('classification', sa.String(length=255), nullable=True),
    sa.Column('archetype', sa.String(length=64), nullable=True),
    sa.Column('hard_veto_status', sa.String(length=64), nullable=True),
    sa.Column('ic_state', sa.String(length=64), nullable=True),
    sa.Column('position_range', sa.String(length=255), nullable=True),
    sa.Column('price_to_base_value', sa.Numeric(precision=18, scale=8, asdecimal=False), nullable=True),
    sa.Column('market_cap_usd', sa.Numeric(precision=28, scale=4, asdecimal=False), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=28, scale=4, asdecimal=False), nullable=True),
    sa.Column('net_cash_per_share', sa.Numeric(precision=28, scale=4, asdecimal=False), nullable=True),
    sa.Column('dilution_watch_status', sa.String(length=64), nullable=True),
    sa.Column('early_exit', sa.Boolean(), nullable=False),
    sa.Column('full_harness_complete', sa.Boolean(), nullable=False),
    sa.Column('triage_complete', sa.Boolean(), nullable=False),
    sa.Column('domain_scores', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('axis_scores', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('strategy_version', sa.String(length=64), nullable=True),
    sa.Column('decision_policy_version', sa.String(length=64), nullable=True),
    sa.Column('code_commit_sha', sa.String(length=64), nullable=True),
    sa.Column('input_snapshot_sha256', sa.String(length=64), nullable=True),
    sa.Column('aggregate_sha256', sa.String(length=64), nullable=False),
    sa.Column('artifact_uri', sa.Text(), nullable=False),
    sa.Column('frozen', sa.Boolean(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['security.security_id'], ),
    sa.PrimaryKeyConstraint('harness_run_id'),
    sa.UniqueConstraint('run_id', 'aggregate_sha256', name='uq_harness_run_version')
    )
    op.create_index('ix_harness_run_asof', 'harness_run', ['as_of_date'], unique=False)
    op.create_index('ix_harness_run_current', 'harness_run', ['ticker', 'is_current'], unique=False)
    op.create_table('market_snapshot',
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=64), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('close', sa.Numeric(precision=28, scale=4, asdecimal=False), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=28, scale=4, asdecimal=False), nullable=True),
    sa.Column('shares_outstanding', sa.Numeric(precision=24, scale=4, asdecimal=False), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['security.security_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id'),
    sa.UniqueConstraint('security_id', 'as_of_date', 'source', name='uq_snapshot_point')
    )
    op.create_index('ix_snapshot_ticker_date', 'market_snapshot', ['ticker', 'as_of_date'], unique=False)
    op.create_table('screening_metric',
    sa.Column('metric_row_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=64), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Numeric(precision=38, scale=10, asdecimal=False), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('method', sa.String(length=255), nullable=True),
    sa.Column('unavailable_reason', sa.Text(), nullable=True),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('provenance', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('inputs_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['security.security_id'], ),
    sa.PrimaryKeyConstraint('metric_row_id'),
    sa.UniqueConstraint('ticker', 'as_of_date', 'metric', name='uq_metric_point')
    )
    op.create_index('ix_metric_lookup', 'screening_metric', ['metric', 'as_of_date', 'value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metric_lookup', table_name='screening_metric')
    op.drop_table('screening_metric')
    op.drop_index('ix_snapshot_ticker_date', table_name='market_snapshot')
    op.drop_table('market_snapshot')
    op.drop_index('ix_harness_run_current', table_name='harness_run')
    op.drop_index('ix_harness_run_asof', table_name='harness_run')
    op.drop_table('harness_run')
    op.drop_index('ix_fact_lookup', table_name='financial_fact')
    op.drop_table('financial_fact')
    op.drop_index('ix_security_ticker', table_name='security')
    op.drop_table('security')
    op.drop_index('ix_filing_issuer_date', table_name='filing')
    op.drop_table('filing')
    op.drop_table('sync_log')
    op.drop_table('screen_run')
    op.drop_index('ix_job_status_kind', table_name='job')
    op.drop_table('job')
    op.drop_table('issuer')
    op.drop_index('ix_deep_dive_ticker', table_name='deep_dive')
    op.drop_table('deep_dive')
    # ### end Alembic commands ###
